# Site setings
name: 'Andreas Schrade'
description: 'Android Freelancer who loves his passion and serves companies all over the world'
meta_description: 'A blog about Android, software development, clean code, the future, the universe... and everything in between'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: http://andreasschrade.com/
disqus: 'andreas-schrade'
mailchimp_url: '//exynap.us14.list-manage.com/subscribe/post?u=be36936da288eb536563e6afd&amp;id=19b27ddc9b'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 'UA-54328989-1' 


# Author
author:
  name: 'Andreas Schrade'
  image: 'authorimage.jpg'
  greetings: 'Hi, I am Andreas!'
  description: |
    <strong>IT Company Owner - Musician - Thinker</strong><br>
    Intrigued by ideas, exciting projects, finance & investing, books, armchair philosophy, creativity, composing and even better conversations.<br>Seeking to be inspired, to envision the unlikely, to work hard for things that are worth it, and to be surrounded by those who bring out the best in me... <a href="/contact/">Send me a message!</a>
  bio: 'IT company owner and enthusiastic Android Developer expert who serve companies in all over the world. Intrigued by ideas, challenging projects, lifelong learning, armchair philosophy, and even better conversations.<br><br>Seeking to be inspired, to envision the unlikely, to work hard for things that are worth it, and to be surrounded by those who bring out the best in me.<br><b><u>Say Hi!</u></b><br><a href="https://twitter.com/andreasschrade">on Twitter @andreasschrade</a><br><a href="http://linkedin.com/in/andreasschrade">on LinkedIn andreasschrade</a><br><a href="/contact/">Contact me!</a>'

# Contact form setings
email: blog@andreas-schrade.de
contact_page_description: "Let's discuss exciting ideas and projects, let's talk about entrepreneuership, marketing, sales, classical music, composition, philosophy, economy, investing, real estate, technology, ..."
thankyou_page_description: "Thanks. Your message has been successfully sent. I will contact you as soon as possible!"

# Social links
twitter: 'andreasschrade'
github: 'andreasschrade'
linkedin: 'andreasschrade'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Contact Me
    url: /contact/
  - text: Privacy Policy
    url: /privacy-policy/
  - text: Impressum
    url: /imprint/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

plugins:
  - jemoji

# Pagination
paginate: 20
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
