# Site setings
name: 'Andreas Schrade'
description: 'Android Freelancer who loves to share his passion'
meta_description: 'A blog about Android, software development, clean code, the future, the universe... and everything in between'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: http://andreas-schrade.de/
disqus: 'andreas-schrade'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 'UA-54328989-1' 


# Author
author:
  name: 'Andreas Schrade'
  image: 'authorimage.jpg'
  greetings: 'Hi, I am Andreas!'
  description: |
    <strong>Freelance Android Expert. Lifelong-Learner. Minimalist. Thinker.</strong><br>
    Intrigued by ideas, exciting projects, finance & investing, books, armchair philosophy, composing, writing, classical music, and even better conversations.<br>Seeking to be inspired, to envision the unlikely, to work hard for things that are worth it, and to be surrounded by those who bring out the best in me... <a href="/contact/">Maybe that's you</a>?
  bio: 'Intrigued by ideas, interesting projects, finance & investing, strategy, books, armchair philosophy, composing, writing, classical music, and even better conversations. Seeking to be inspired, to envision the unlikely, to work hard for things that are worth it, and to be surrounded by those who bring out the best in me.'

# Contact form setings
email: blog@andreas-schrade.de
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'andreasschrade'
github: 'andreasschrade'
linkedin: 'andreasschrade'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Contact Me
    url: /contact/
  - text: Style Guide
    url: /style-guide/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 20
paginate_path: /page:num/

# Permalinks
permalink: /:year/:month/:day/:title/

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
