# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Andreas Schrade
tagline:          ein Blog über Java- und Android-Entwicklung
url:              http://andreasschrade.de
paginate:         1
baseurl:          /
author:
  name:           Andreas Schrade
  url:            http://andreasschrade.de
  email:          blog@andreasschrade.de

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/andreasschrade/andreasschrade.github.com

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
  Impressum: '/impressum'