# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Andreas Schrade
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Andreas Schrade
  url:            http://andreasschrade.de
  email:          blog@andreasschrade.de

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/andreasschrade/andreasschrade.github.com
